### ISSUE TITLE
Category._id没找到怎么用;有的Category是网页,但封装后得不到链接

### ISSUE THREAD

**Issue by 4ragaki** [ShirosakiMieru/PicaComic-Api#11]
![image](https://user-images.githubusercontent.com/23445216/61170003-f45daa00-a595-11e9-9d9b-a6c433e07958.png)

![image](https://user-images.githubusercontent.com/23445216/61170011-0fc8b500-a596-11e9-8c49-02c5f7551df5.png)
Category属性不够而且JsonObject没有暴露

另Category._id这个属性没找到有关的Api

**Comment by ShirosakiMieru** [comment]
感谢反馈，新的getter已添加到[**v2.0.1**][1]版本。

[1]: https://github.com/ShirosakiMieru/PicaComic-Api/releases/tag/v2.0.1

**Comment by 4ragaki** [comment]
还有一个问题,category这个类的对象怎么使用?

**Comment by ShirosakiMieru** [comment]
> 还有一个问题,category这个类的对象怎么使用?

这个类只是封装了搜索界面的每个类型的信息，本质上这些类型（比如妹系、姐系）点进去都是调用的关键词搜索。部分类型有不同的url（例如哔咔AI推荐），这些应该是编码在客户端里的，我这边没有抓包到相关的请求URL。

**Comment by 4ragaki** [comment]
好的,感谢.
