### ISSUE TITLE
登陆失败 PicaException

### ISSUE THREAD

**Issue by zzZ5** [ShirosakiMieru/PicaComic-Api#12]
今天用的时候每次登陆都报PicaException，我用手机登录软件看了一下，应该是强制版本更新导致的

**Comment by ShirosakiMieru** [comment]
应该是哔咔更新了接口，已经在处理了

**Comment by ShirosakiMieru** [comment]
哔咔更新了签名算法，可能需要一段时间才能破解

**Comment by Aloxaf** [comment]
https://github.com/ShirosakiMieru/PicaComic-Api/commit/338539abe428e4e42d1c52e16a58ac1a985ced63 ...刚发现这个项目, 怎么就凉了呢 orz

**Comment by SodiumAzide** [comment]
https://github.com/SodiumAzide/picacomic/blob/master/test.py
开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过

**Comment by ShirosakiMieru** [comment]
> https://github.com/SodiumAzide/picacomic/blob/master/test.py
> 开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过

app-uuid是随机的，可以自己生成，build_version是42，低于这个版本会跳出更新提示，version是2.2.0.0.1.1，单独修改这个没有什么影响，secret_Key这个是native方法，因为本人技术有限暂时无法获取到....

**Comment by SodiumAzide** [comment]
> > https://github.com/SodiumAzide/picacomic/blob/master/test.py
> > 开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过
> 
> app-uuid是随机的，可以自己生成，build_version是42，低于这个版本会跳出更新提示，version是2.2.0.0.1.1，单独修改这个没有什么影响，secret_Key这个是native方法，因为本人技术有限暂时无法获取到....

已发送PR

**Comment by Aloxaf** [comment]
> https://github.com/SodiumAzide/picacomic/blob/master/test.py
> 开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过

这个 key 我也逆出来了, 但是不知道是不是我的脚本写得有问题, 登录结果一直都是 `{'code': 200, 'message': 'success'}`, 不管密码对不对...
莫非哔咔还在哪里动了什么手脚?

**Comment by Aloxaf** [comment]
> > https://github.com/SodiumAzide/picacomic/blob/master/test.py
> > 开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过
> 
> 这个 key 我也逆出来了, 但是不知道是不是我的脚本写得有问题, 登录结果一直都是 `{'code': 200, 'message': 'success'}`, 不管密码对不对...
> 莫非哔咔还在哪里动了什么手脚?

艹, 似乎是我个辣鸡脚本写得有问题...

**Comment by SodiumAzide** [comment]
> > https://github.com/SodiumAzide/picacomic/blob/master/test.py
> > 开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过
> 
> 这个 key 我也逆出来了, 但是不知道是不是我的脚本写得有问题, 登录结果一直都是 `{'code': 200, 'message': 'success'}`, 不管密码对不对...
> 莫非哔咔还在哪里动了什么手脚?

我自己用的golang实现的，替换一下就可以使用了。你试试app-uuid写死？我记得抓包时，appuuid是不会变的

**Comment by Aloxaf** [comment]
> > > https://github.com/SodiumAzide/picacomic/blob/master/test.py
> > > 开发者，加油！注意app-uuid，build_version，version，secret_key都改了。本人已使用golang测试通过
> > 
> > 
> > 这个 key 我也逆出来了, 但是不知道是不是我的脚本写得有问题, 登录结果一直都是 `{'code': 200, 'message': 'success'}`, 不管密码对不对...
> > 莫非哔咔还在哪里动了什么手脚?
> 
> 我自己用的golang实现的，替换一下就可以使用了。你试试app-uuid写死？我记得抓包时，appuuid是不会变的

试了一下你这里面的脚本改完 secret_key 等项就能登录了, 应该我自己脚本写错了orz...

**Comment by kaaass** [comment]
新sk昨天晚上我自己拼了一下，博客已经更新。
另附接口文档，希望能帮到你：http://docs.kaaass.net/showdoc/web/#/8
密码：1145141919
接口已经更新到船新版本了。文档请勿扩散。

**Comment by kaaass** [comment]
另外，有兴趣逆向做map的欢迎联系我。

**Comment by kaaass** [comment]
@ShirosakiMieru app-uuid是设备uuid。

**Comment by Aloxaf** [comment]
> 新sk昨天晚上我自己拼了一下，博客已经更新。
> 另附接口文档，希望能帮到你：http://docs.kaaass.net/showdoc/web/#/8
> 密码：1145141919
> 接口已经更新到船新版本了。文档请勿扩散。https://paste.gg/p/anonymous/278dcb91bd8c47aeaa4dc6403a9a59de

感谢大佬(<del>就是密码有点恶臭 </del>

顺便能否请教一个问题:
我在使用 search/advanced-search 查询时返回的结果总是没有 data 字段(`{'code': 200, 'message': 'success'}`), 是否有其他需要注意的地方? (还是我个辣鸡代码又写错了....

部分代码:
https://paste.gg/p/anonymous/6fe904cb22434928a406dc223838482c

**Comment by kaaass** [comment]
> > 新sk昨天晚上我自己拼了一下，博客已经更新。
> > 另附接口文档，希望能帮到你：http://docs.kaaass.net/showdoc/web/#/8
> > 密码：1145141919
> > 接口已经更新到船新版本了。文档请勿扩散。https://paste.gg/p/anonymous/278dcb91bd8c47aeaa4dc6403a9a59de
> 
> 感谢大佬(~就是密码有点恶臭 ~
> 
> 顺便能否请教一个问题:
> 我在使用 search/advanced-search 查询时返回的结果总是没有 data 字段(`{'code': 200, 'message': 'success'}`), 是否有其他需要注意的地方? (还是我个辣鸡代码又写错了....
> 
> 部分代码:
> https://paste.gg/p/anonymous/6fe904cb22434928a406dc223838482c

我可能没写清楚。post采用raw形式，把data转成json字符串再传入就可以了。

**Comment by Aloxaf** [comment]
@kaaass soga，谢谢！

**Comment by ShirosakiMieru** [comment]
感谢各位dalao帮助，问题已修复~
